package gutta.apievolution.cobol;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.1 Build 20180227-1206 on: Fri Jan 21 15:10:56 CET 2022

public class KundeRecResolution {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 
	static { factory.setStringEncoding("IBM-1141"); } 

	/** <pre>
	 01  My-Data-Structure. </pre> */
	public static final int MY_DATA_STRUCTURE_len = 982; 

	/** <pre>
	     COPY KUNDERES.
	
	  05  Kunde. </pre> */
	public static final int KUNDE_len = 982; 
	public static final int KUNDE_offset = factory.getOffset();

	/** <pre>
	    10  Name. </pre> */
	public static final int NAME_len = 161; 
	public static final int NAME_offset = factory.getOffset();

	/** <pre>
	      15  Vorname   PIC X(64). </pre> */
	protected static final StringField VORNAME = factory.getStringField(64);

	/** <pre>
	      15  FILLER   PIC X(1). </pre> */
	protected static final StringField FILLER_1 = factory.getStringField(1);

	/** <pre>
	      15  NachnameProlonged   PIC X(64). </pre> */
	protected static final StringField NACHNAMEPROLONGED = factory.getStringField(64);

	/** <pre>
	      15  Nachname   PIC X(32). </pre> */
	protected static final StringField NACHNAME = factory.getStringField(32);

	/** <pre>
	    10  GeburtsdatumNew. </pre> */
	public static final int GEBURTSDATUMNEW_len = 10; 
	public static final int GEBURTSDATUMNEW_offset = factory.getOffset();

	/** <pre>
	      15  GeburtsdatumTag   PIC 9(2). </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUMTAG = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	      15  FILLER   PIC X(1). </pre> */
	protected static final StringField FILLER_2 = factory.getStringField(1);

	/** <pre>
	      15  GeburtsdatumMonat   PIC 9(2). </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUMMONAT = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	      15  FILLER1   PIC X(1). </pre> */
	protected static final StringField FILLER1 = factory.getStringField(1);

	/** <pre>
	      15  GeburtsdatumJahr   PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUMJAHR = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	    10  Festnetznummer   PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField FESTNETZNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	    10  Mobilfunknummer   PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField MOBILFUNKNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	    10  MailadresseShortened   PIC X(256). </pre> */
	protected static final StringField MAILADRESSESHORTENED = factory.getStringField(256);

	/** <pre>
	    10  Geburtsdatum   PIC X(10). </pre> */
	protected static final StringField GEBURTSDATUM = factory.getStringField(10);

	/** <pre>
	    10  Geschlecht   PIC X(1). </pre> */
	protected static final StringField GESCHLECHT = factory.getStringField(1);

	/** <pre>
	    10  Mailadresse   PIC X(512). </pre> */
	protected static final StringField MAILADRESSE = factory.getStringField(512);

	protected byte[] _byteBuffer;


	public KundeRecResolution (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public KundeRecResolution () {
		this._byteBuffer = new byte[MY_DATA_STRUCTURE_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getVorname() {
		return VORNAME.getString(_byteBuffer);
	}

	public void setVorname(String vorname) {
		VORNAME.putString(vorname, _byteBuffer);
	}

	public String getFiller_1() {
		return FILLER_1.getString(_byteBuffer);
	}

	public void setFiller_1(String filler_1) {
		FILLER_1.putString(filler_1, _byteBuffer);
	}

	public String getNachnameprolonged() {
		return NACHNAMEPROLONGED.getString(_byteBuffer);
	}

	public void setNachnameprolonged(String nachnameprolonged) {
		NACHNAMEPROLONGED.putString(nachnameprolonged, _byteBuffer);
	}

	public String getNachname() {
		return NACHNAME.getString(_byteBuffer);
	}

	public void setNachname(String nachname) {
		NACHNAME.putString(nachname, _byteBuffer);
	}

	public int getGeburtsdatumtag() {
		return GEBURTSDATUMTAG.getInt(_byteBuffer);
	}

	public void setGeburtsdatumtag(int geburtsdatumtag) {
		GEBURTSDATUMTAG.putInt(geburtsdatumtag, _byteBuffer);
	}

	public String getFiller_2() {
		return FILLER_2.getString(_byteBuffer);
	}

	public void setFiller_2(String filler_2) {
		FILLER_2.putString(filler_2, _byteBuffer);
	}

	public int getGeburtsdatummonat() {
		return GEBURTSDATUMMONAT.getInt(_byteBuffer);
	}

	public void setGeburtsdatummonat(int geburtsdatummonat) {
		GEBURTSDATUMMONAT.putInt(geburtsdatummonat, _byteBuffer);
	}

	public String getFiller1() {
		return FILLER1.getString(_byteBuffer);
	}

	public void setFiller1(String filler1) {
		FILLER1.putString(filler1, _byteBuffer);
	}

	public int getGeburtsdatumjahr() {
		return GEBURTSDATUMJAHR.getInt(_byteBuffer);
	}

	public void setGeburtsdatumjahr(int geburtsdatumjahr) {
		GEBURTSDATUMJAHR.putInt(geburtsdatumjahr, _byteBuffer);
	}

	public long getFestnetznummer() {
		return FESTNETZNUMMER.getLong(_byteBuffer);
	}

	public void setFestnetznummer(long festnetznummer) {
		FESTNETZNUMMER.putLong(festnetznummer, _byteBuffer);
	}

	public long getMobilfunknummer() {
		return MOBILFUNKNUMMER.getLong(_byteBuffer);
	}

	public void setMobilfunknummer(long mobilfunknummer) {
		MOBILFUNKNUMMER.putLong(mobilfunknummer, _byteBuffer);
	}

	public String getMailadresseshortened() {
		return MAILADRESSESHORTENED.getString(_byteBuffer);
	}

	public void setMailadresseshortened(String mailadresseshortened) {
		MAILADRESSESHORTENED.putString(mailadresseshortened, _byteBuffer);
	}

	public String getGeburtsdatum() {
		return GEBURTSDATUM.getString(_byteBuffer);
	}

	public void setGeburtsdatum(String geburtsdatum) {
		GEBURTSDATUM.putString(geburtsdatum, _byteBuffer);
	}

	public String getGeschlecht() {
		return GESCHLECHT.getString(_byteBuffer);
	}

	public void setGeschlecht(String geschlecht) {
		GESCHLECHT.putString(geschlecht, _byteBuffer);
	}

	public String getMailadresse() {
		return MAILADRESSE.getString(_byteBuffer);
	}

	public void setMailadresse(String mailadresse) {
		MAILADRESSE.putString(mailadresse, _byteBuffer);
	}

}
