package gutta.apievolution.cobol;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.1 Build 20180227-1206 on: Mon Jan 17 20:08:35 CET 2022

public class KundeRecResolution {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); }
	static { factory.setStringEncoding("IBM-1141"); }

	/** <pre>
	 01  My-Data-Structure. </pre> */
	public static final int MY_DATA_STRUCTURE_len = 1143;

	/** <pre>
	     COPY KUNDERES.
	     05  Kunde. </pre> */
	public static final int KUNDE_len = 1143;
	public static final int KUNDE_offset = factory.getOffset();

	/** <pre>
	         10  NameNew. </pre> */
	public static final int NAMENEW_len = 161;
	public static final int NAMENEW_offset = factory.getOffset();

	/** <pre>
	             15  Vorname             PIC X(64). </pre> */
	protected static final StringField VORNAME_In_NAMENEW = factory.getStringField(64);

	/** <pre>
	             15  FILLER              PIC X. </pre> */
	protected static final StringField FILLER_1 = factory.getStringField(1);

	/** <pre>
	             15  NachnameProlonged   PIC X(64). </pre> */
	protected static final StringField NACHNAMEPROLONGED_In_NAMENEW = factory.getStringField(64);

	/** <pre>
	             15  Nachname            PIC X(32). </pre> */
	protected static final StringField NACHNAME_In_NAMENEW = factory.getStringField(32);

	/** <pre>
	         10  Geburtsdatum. </pre> */
	public static final int GEBURTSDATUM_In_KUNDE_len = 10;
	public static final int GEBURTSDATUM_In_KUNDE_offset = factory.getOffset();

	/** <pre>
	             15  Geburtsdatum-Tag    PIC 99. </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_TAG = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	             15  FILLER              PIC X    VALUE ':'. </pre> */
	protected static final StringField FILLER_2 = factory.getStringField(1);
	public static final String FILLER_2_ival = ":";

	/** <pre>
	             15  Geburtsdatum-Monat  PIC 99. </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_MONAT = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	             15  FILLER              PIC X    VALUE ':'. </pre> */
	protected static final StringField FILLER_3 = factory.getStringField(1);
	public static final String FILLER_3_ival = ":";

	/** <pre>
	             15  Geburtsdatum-Jahr   PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_JAHR = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	         10  Festnetznummer          PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField FESTNETZNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	         10  Mobilfunknummer         PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField MOBILFUNKNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	         10  MailadresseShortened    PIC X(256). </pre> */
	protected static final StringField MAILADRESSESHORTENED = factory.getStringField(256);

	/** <pre>
	         10  Name. </pre> */
	public static final int NAME_len = 161;
	public static final int NAME_offset = factory.getOffset();

	/** <pre>
	             15  Vorname             PIC X(64). </pre> */
	protected static final StringField VORNAME_In_NAME = factory.getStringField(64);

	/** <pre>
	             15  FILLER              PIC X. </pre> */
	protected static final StringField FILLER_4 = factory.getStringField(1);

	/** <pre>
	             15  NachnameProlonged   PIC X(64). </pre> */
	protected static final StringField NACHNAMEPROLONGED_In_NAME = factory.getStringField(64);

	/** <pre>
	             15  Nachname            PIC X(32). </pre> */
	protected static final StringField NACHNAME_In_NAME = factory.getStringField(32);

	/** <pre>
	         10  Geburtsdatum            PIC X(10). </pre> */
	protected static final StringField GEBURTSDATUM_In_KUNDE = factory.getStringField(10);

	/** <pre>
	         10  Geschlecht              PIC X. </pre> */
	protected static final StringField GESCHLECHT = factory.getStringField(1);

	/** <pre>
	             88  Maennlich                    VALUE 'M'. </pre> */
	public static final String MAENNLICH = "M";

	/** <pre>
	             88  Weiblich                     VALUE 'W'. </pre> */
	public static final String WEIBLICH = "W";

	/** <pre>
	         10  Mailadresse             PIC X(512). </pre> */
	protected static final StringField MAILADRESSE = factory.getStringField(512);

	protected byte[] _byteBuffer;


	public KundeRecResolution (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public KundeRecResolution () {
		this._byteBuffer = new byte[MY_DATA_STRUCTURE_len];
		setInitialValues();
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}

	public void setInitialValues() {
		setFiller_2(FILLER_2_ival);
		setFiller_3(FILLER_3_ival);
	}


	public String getVorname_In_Namenew() {
		return VORNAME_In_NAMENEW.getString(_byteBuffer);
	}

	public void setVorname_In_Namenew(String vorname_In_namenew) {
		VORNAME_In_NAMENEW.putString(vorname_In_namenew, _byteBuffer);
	}

	public String getFiller_1() {
		return FILLER_1.getString(_byteBuffer);
	}

	public void setFiller_1(String filler_1) {
		FILLER_1.putString(filler_1, _byteBuffer);
	}

	public String getNachnameprolonged_In_Namenew() {
		return NACHNAMEPROLONGED_In_NAMENEW.getString(_byteBuffer);
	}

	public void setNachnameprolonged_In_Namenew(String nachnameprolonged_In_namenew) {
		NACHNAMEPROLONGED_In_NAMENEW.putString(nachnameprolonged_In_namenew, _byteBuffer);
	}

	public String getNachname_In_Namenew() {
		return NACHNAME_In_NAMENEW.getString(_byteBuffer);
	}

	public void setNachname_In_Namenew(String nachname_In_namenew) {
		NACHNAME_In_NAMENEW.putString(nachname_In_namenew, _byteBuffer);
	}

	public int getGeburtsdatumTag() {
		return GEBURTSDATUM_TAG.getInt(_byteBuffer);
	}

	public void setGeburtsdatumTag(int geburtsdatumTag) {
		GEBURTSDATUM_TAG.putInt(geburtsdatumTag, _byteBuffer);
	}

	public String getFiller_2() {
		return FILLER_2.getString(_byteBuffer);
	}

	public void setFiller_2(String filler_2) {
		FILLER_2.putString(filler_2, _byteBuffer);
	}

	public int getGeburtsdatumMonat() {
		return GEBURTSDATUM_MONAT.getInt(_byteBuffer);
	}

	public void setGeburtsdatumMonat(int geburtsdatumMonat) {
		GEBURTSDATUM_MONAT.putInt(geburtsdatumMonat, _byteBuffer);
	}

	public String getFiller_3() {
		return FILLER_3.getString(_byteBuffer);
	}

	public void setFiller_3(String filler_3) {
		FILLER_3.putString(filler_3, _byteBuffer);
	}

	public int getGeburtsdatumJahr() {
		return GEBURTSDATUM_JAHR.getInt(_byteBuffer);
	}

	public void setGeburtsdatumJahr(int geburtsdatumJahr) {
		GEBURTSDATUM_JAHR.putInt(geburtsdatumJahr, _byteBuffer);
	}

	public long getFestnetznummer() {
		return FESTNETZNUMMER.getLong(_byteBuffer);
	}

	public void setFestnetznummer(long festnetznummer) {
		FESTNETZNUMMER.putLong(festnetznummer, _byteBuffer);
	}

	public long getMobilfunknummer() {
		return MOBILFUNKNUMMER.getLong(_byteBuffer);
	}

	public void setMobilfunknummer(long mobilfunknummer) {
		MOBILFUNKNUMMER.putLong(mobilfunknummer, _byteBuffer);
	}

	public String getMailadresseshortened() {
		return MAILADRESSESHORTENED.getString(_byteBuffer);
	}

	public void setMailadresseshortened(String mailadresseshortened) {
		MAILADRESSESHORTENED.putString(mailadresseshortened, _byteBuffer);
	}

	public String getVorname_In_Name() {
		return VORNAME_In_NAME.getString(_byteBuffer);
	}

	public void setVorname_In_Name(String vorname_In_name) {
		VORNAME_In_NAME.putString(vorname_In_name, _byteBuffer);
	}

	public String getFiller_4() {
		return FILLER_4.getString(_byteBuffer);
	}

	public void setFiller_4(String filler_4) {
		FILLER_4.putString(filler_4, _byteBuffer);
	}

	public String getNachnameprolonged_In_Name() {
		return NACHNAMEPROLONGED_In_NAME.getString(_byteBuffer);
	}

	public void setNachnameprolonged_In_Name(String nachnameprolonged_In_name) {
		NACHNAMEPROLONGED_In_NAME.putString(nachnameprolonged_In_name, _byteBuffer);
	}

	public String getNachname_In_Name() {
		return NACHNAME_In_NAME.getString(_byteBuffer);
	}

	public void setNachname_In_Name(String nachname_In_name) {
		NACHNAME_In_NAME.putString(nachname_In_name, _byteBuffer);
	}

	public String getGeburtsdatum_In_Kunde() {
		return GEBURTSDATUM_In_KUNDE.getString(_byteBuffer);
	}

	public void setGeburtsdatum_In_Kunde(String geburtsdatum_In_kunde) {
		GEBURTSDATUM_In_KUNDE.putString(geburtsdatum_In_kunde, _byteBuffer);
	}

	public String getGeschlecht() {
		return GESCHLECHT.getString(_byteBuffer);
	}

	public void setGeschlecht(String geschlecht) {
		GESCHLECHT.putString(geschlecht, _byteBuffer);
	}

	public boolean isMaennlich() {
		return getGeschlecht().equals(MAENNLICH);
	}

	public boolean isWeiblich() {
		return getGeschlecht().equals(WEIBLICH);
	}

	public String getMailadresse() {
		return MAILADRESSE.getString(_byteBuffer);
	}

	public void setMailadresse(String mailadresse) {
		MAILADRESSE.putString(mailadresse, _byteBuffer);
	}

}
