package gutta.apievolution.cobol;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.1 Build 20180227-1206 on: Sun Jan 16 01:35:30 CET 2022

public class KundeRecRevision1 {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); }
	static { factory.setStringEncoding("IBM-1141"); }

	/** <pre>
	 01  My-Data-Structure. </pre> */
	public static final int MY_DATA_STRUCTURE_len = 636;

	/** <pre>
	     COPY KUNDE001.
	     05  Kunde. </pre> */
	public static final int KUNDE_len = 636;
	public static final int KUNDE_offset = factory.getOffset();

	/** <pre>
	         10  Name. </pre> */
	public static final int NAME_len = 97;
	public static final int NAME_offset = factory.getOffset();

	/** <pre>
	             15  Vorname         PIC X(64). </pre> */
	protected static final StringField VORNAME = factory.getStringField(64);

	/** <pre>
	             15  FILLER          PIC X. </pre> */
	protected static final StringField FILLER_1 = factory.getStringField(1);

	/** <pre>
	             15  Nachname        PIC X(32). </pre> */
	protected static final StringField NACHNAME = factory.getStringField(32);

	/** <pre>
	         10  Geburtsdatum        PIC X(10). </pre> */
	protected static final StringField GEBURTSDATUM = factory.getStringField(10);

	/** <pre>
	         10  Geschlecht          PIC X. </pre> */
	protected static final StringField GESCHLECHT = factory.getStringField(1);

	/** <pre>
	             88  Maennlich                  VALUE 'M'. </pre> */
	public static final String MAENNLICH = "M";

	/** <pre>
	             88  Weiblich                   VALUE 'W'. </pre> */
	public static final String WEIBLICH = "W";

	/** <pre>
	         10  Telefonnummer       PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField TELEFONNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	         10  Mailadresse         PIC X(512). </pre> */
	protected static final StringField MAILADRESSE = factory.getStringField(512);

	protected byte[] _byteBuffer;


	public KundeRecRevision1 (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public KundeRecRevision1 () {
		this._byteBuffer = new byte[MY_DATA_STRUCTURE_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getVorname() {
		return VORNAME.getString(_byteBuffer);
	}

	public void setVorname(String vorname) {
		VORNAME.putString(vorname, _byteBuffer);
	}

	public String getFiller_1() {
		return FILLER_1.getString(_byteBuffer);
	}

	public void setFiller_1(String filler_1) {
		FILLER_1.putString(filler_1, _byteBuffer);
	}

	public String getNachname() {
		return NACHNAME.getString(_byteBuffer);
	}

	public void setNachname(String nachname) {
		NACHNAME.putString(nachname, _byteBuffer);
	}

	public String getGeburtsdatum() {
		return GEBURTSDATUM.getString(_byteBuffer);
	}

	public void setGeburtsdatum(String geburtsdatum) {
		GEBURTSDATUM.putString(geburtsdatum, _byteBuffer);
	}

	public String getGeschlecht() {
		return GESCHLECHT.getString(_byteBuffer);
	}

	public void setGeschlecht(String geschlecht) {
		GESCHLECHT.putString(geschlecht, _byteBuffer);
	}

	public boolean isMaennlich() {
		return getGeschlecht().equals(MAENNLICH);
	}

	public boolean isWeiblich() {
		return getGeschlecht().equals(WEIBLICH);
	}

	public long getTelefonnummer() {
		return TELEFONNUMMER.getLong(_byteBuffer);
	}

	public void setTelefonnummer(long telefonnummer) {
		TELEFONNUMMER.putLong(telefonnummer, _byteBuffer);
	}

	public String getMailadresse() {
		return MAILADRESSE.getString(_byteBuffer);
	}

	public void setMailadresse(String mailadresse) {
		MAILADRESSE.putString(mailadresse, _byteBuffer);
	}

}
