package gutta.apievolution.cobol;
import com.ibm.jzos.fields.*;

// Generated by IBM Record Generator for Java V3.0.1 Build 20180227-1206 on: Sun Jan 16 17:12:30 CET 2022

public class KundeRecRevision2 {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); }
	static { factory.setStringEncoding("IBM-1141"); }

	/** <pre>
	 01  My-Data-Structure. </pre> */
	public static final int MY_DATA_STRUCTURE_len = 427;

	/** <pre>
	     COPY KUNDE002.
	     05  Kunde. </pre> */
	public static final int KUNDE_len = 427;
	public static final int KUNDE_offset = factory.getOffset();

	/** <pre>
	         10  Name. </pre> */
	public static final int NAME_len = 129;
	public static final int NAME_offset = factory.getOffset();

	/** <pre>
	             15  Vorname             PIC X(64). </pre> */
	protected static final StringField VORNAME = factory.getStringField(64);

	/** <pre>
	             15  FILLER              PIC X. </pre> */
	protected static final StringField FILLER_1 = factory.getStringField(1);

	/** <pre>
	             15  Nachname            PIC X(64). </pre> */
	protected static final StringField NACHNAME = factory.getStringField(64);

	/** <pre>
	         10  Geburtsdatum. </pre> */
	public static final int GEBURTSDATUM_len = 10;
	public static final int GEBURTSDATUM_offset = factory.getOffset();

	/** <pre>
	             15  Geburtsdatum-Tag    PIC 99. </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_TAG = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	             15  FILLER              PIC X    VALUE ':'. </pre> */
	protected static final StringField FILLER_2 = factory.getStringField(1);
	public static final String FILLER_2_ival = ":";

	/** <pre>
	             15  Geburtsdatum-Monat  PIC 99. </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_MONAT = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	             15  FILLER              PIC X    VALUE ':'. </pre> */
	protected static final StringField FILLER_3 = factory.getStringField(1);
	public static final String FILLER_3_ival = ":";

	/** <pre>
	             15  Geburtsdatum-Jahr   PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField GEBURTSDATUM_JAHR = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	         10  Festnetznummer          PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField FESTNETZNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	         10  Mobilfunknummer         PIC 9(16). </pre> */
	protected static final ExternalDecimalAsLongField MOBILFUNKNUMMER = factory.getExternalDecimalAsLongField(16, false, false, false, false);

	/** <pre>
	         10  Mailadresse             PIC X(256). </pre> */
	protected static final StringField MAILADRESSE = factory.getStringField(256);

	protected byte[] _byteBuffer;


	public KundeRecRevision2 (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public KundeRecRevision2 () {
		this._byteBuffer = new byte[MY_DATA_STRUCTURE_len];
		setInitialValues();
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}

	public void setInitialValues() {
		setFiller_2(FILLER_2_ival);
		setFiller_3(FILLER_3_ival);
	}


	public String getVorname() {
		return VORNAME.getString(_byteBuffer);
	}

	public void setVorname(String vorname) {
		VORNAME.putString(vorname, _byteBuffer);
	}

	public String getFiller_1() {
		return FILLER_1.getString(_byteBuffer);
	}

	public void setFiller_1(String filler_1) {
		FILLER_1.putString(filler_1, _byteBuffer);
	}

	public String getNachname() {
		return NACHNAME.getString(_byteBuffer);
	}

	public void setNachname(String nachname) {
		NACHNAME.putString(nachname, _byteBuffer);
	}

	public int getGeburtsdatumTag() {
		return GEBURTSDATUM_TAG.getInt(_byteBuffer);
	}

	public void setGeburtsdatumTag(int geburtsdatumTag) {
		GEBURTSDATUM_TAG.putInt(geburtsdatumTag, _byteBuffer);
	}

	public String getFiller_2() {
		return FILLER_2.getString(_byteBuffer);
	}

	public void setFiller_2(String filler_2) {
		FILLER_2.putString(filler_2, _byteBuffer);
	}

	public int getGeburtsdatumMonat() {
		return GEBURTSDATUM_MONAT.getInt(_byteBuffer);
	}

	public void setGeburtsdatumMonat(int geburtsdatumMonat) {
		GEBURTSDATUM_MONAT.putInt(geburtsdatumMonat, _byteBuffer);
	}

	public String getFiller_3() {
		return FILLER_3.getString(_byteBuffer);
	}

	public void setFiller_3(String filler_3) {
		FILLER_3.putString(filler_3, _byteBuffer);
	}

	public int getGeburtsdatumJahr() {
		return GEBURTSDATUM_JAHR.getInt(_byteBuffer);
	}

	public void setGeburtsdatumJahr(int geburtsdatumJahr) {
		GEBURTSDATUM_JAHR.putInt(geburtsdatumJahr, _byteBuffer);
	}

	public long getFestnetznummer() {
		return FESTNETZNUMMER.getLong(_byteBuffer);
	}

	public void setFestnetznummer(long festnetznummer) {
		FESTNETZNUMMER.putLong(festnetznummer, _byteBuffer);
	}

	public long getMobilfunknummer() {
		return MOBILFUNKNUMMER.getLong(_byteBuffer);
	}

	public void setMobilfunknummer(long mobilfunknummer) {
		MOBILFUNKNUMMER.putLong(mobilfunknummer, _byteBuffer);
	}

	public String getMailadresse() {
		return MAILADRESSE.getString(_byteBuffer);
	}

	public void setMailadresse(String mailadresse) {
		MAILADRESSE.putString(mailadresse, _byteBuffer);
	}

}
